services:
  livestatus_go:
    image: ghcr.io/antoninhuaut/livestatusgo:master
    container_name: clivestatus_go
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:8080"
