services:
  livestatus:
    image: ghcr.io/antoninhuaut/livestatus:master
    container_name: clivestatus
    restart: unless-stopped
    volumes:
      - ./storage:/app/storage
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:8080"
